# application.properties
spring.application.name=M8Project

# Recreate schema on each run at startup
spring.jpa.hibernate.ddl-auto=create

# Disable Open Session in View
spring.jpa.open-in-view=false

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Ensure data.sql is always executed (even with JPA/Hibernate)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.config.activate.on-profile=!test

# Stop Spring from printing long "Resolved [MethodArgumentNotValidException]" warnings
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR